# Generated by Django 2.0.2 on 2018-02-21 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('response', models.TextField()),
                ('sequence', models.TextField()),
                ('dumped_sequence', models.TextField()),
                ('malware', models.BooleanField()),
                ('run_pe', models.BooleanField()),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
