# Generated by Django 2.0.2 on 2018-02-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='PEFile',
        ),
    ]
