# Generated by Django 2.0.2 on 2018-02-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180221_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pefile',
            name='malware',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pefile',
            name='run_pe',
            field=models.BooleanField(default=False),
        ),
    ]
