# Generated by Django 2.0.2 on 2018-02-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180221_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pefile',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
