# Generated by Django 2.0.3 on 2018-03-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180221_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pefile',
            old_name='dumped_sequence',
            new_name='runpe_sequence',
        ),
        migrations.AddField(
            model_name='pefile',
            name='runpe_file',
            field=models.FileField(default='', upload_to='extracted'),
            preserve_default=False,
        ),
    ]
