# Generated by Django 2.0.3 on 2018-03-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180318_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='pefile',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
