# Generated by Django 2.0.3 on 2018-03-18 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pefile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('arch', models.CharField(max_length=255)),
                ('response', models.TextField()),
                ('file', models.FileField(upload_to='dataset')),
                ('sequence', models.TextField()),
                ('runpe_file', models.FileField(upload_to='extracted')),
                ('runpe_sequence', models.TextField()),
                ('malware', models.BooleanField(default=False)),
                ('run_pe', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='PEFile',
        ),
    ]
