# Generated by Django 2.0.3 on 2018-03-19 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180318_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='time',
            new_name='created_time',
        ),
        migrations.AddField(
            model_name='record',
            name='updated_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
