# Generated by Django 2.0.3 on 2018-03-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180319_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='runpe_file',
            new_name='run_pe_file',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='runpe_sequence',
            new_name='run_pe_sequence',
        ),
        migrations.AddField(
            model_name='record',
            name='screen_shot',
            field=models.FileField(default='', upload_to='screenshot'),
            preserve_default=False,
        ),
    ]
