# Generated by Django 2.0.3 on 2018-03-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180319_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='vbox',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
