# Generated by Django 2.0.3 on 2018-03-25 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180325_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='record',
            name='updated_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
