# Generated by Django 2.0.3 on 2018-03-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='power',
            field=models.IntegerField(default=0),
        ),
    ]
